import { MigrationInterface, QueryRunner } from 'typeorm';
export class CreateInventoryRevaluation1787609000000 implements MigrationInterface {
  name = 'CreateInventoryRevaluation1787609000000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TYPE "inventory_revaluation_status_enum" AS ENUM ('draft','posted')`);
    await q.query(`CREATE TABLE "inventory_revaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "revaluation_number" varchar(50) NOT NULL, "revaluation_date" date NOT NULL, "status" "inventory_revaluation_status_enum" NOT NULL DEFAULT 'draft', "gain_account_id" uuid NOT NULL, "loss_account_id" uuid NOT NULL, "currency" varchar(3) NOT NULL DEFAULT 'EUR', "total_increase" numeric(18,4) NOT NULL DEFAULT 0, "total_decrease" numeric(18,4) NOT NULL DEFAULT 0, "journal_entry_id" uuid, "notes" text, "created_by" uuid, "posted_by" uuid, "posted_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "PK_inventory_revaluations" PRIMARY KEY ("id"), CONSTRAINT "UQ_inventory_revaluations_company_number" UNIQUE ("company_id","revaluation_number"))`);
    await q.query(`CREATE INDEX "IDX_inventory_revaluations_company_date" ON "inventory_revaluations" ("company_id","revaluation_date")`);
    await q.query(`CREATE TABLE "inventory_revaluation_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "revaluation_id" uuid NOT NULL, "item_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "quantity" numeric(18,4) NOT NULL, "old_unit_cost" numeric(18,6) NOT NULL, "new_unit_cost" numeric(18,6) NOT NULL, "old_value" numeric(18,4) NOT NULL, "new_value" numeric(18,4) NOT NULL, "adjustment_amount" numeric(18,4) NOT NULL, CONSTRAINT "PK_inventory_revaluation_lines" PRIMARY KEY ("id"), CONSTRAINT "UQ_inventory_revaluation_lines_item_warehouse" UNIQUE ("revaluation_id","item_id","warehouse_id"), CONSTRAINT "FK_inventory_revaluation_lines_header" FOREIGN KEY ("revaluation_id") REFERENCES "inventory_revaluations"("id") ON DELETE CASCADE)`);
  }
  async down(q: QueryRunner): Promise<void> { await q.query(`DROP TABLE "inventory_revaluation_lines"`); await q.query(`DROP INDEX "IDX_inventory_revaluations_company_date"`); await q.query(`DROP TABLE "inventory_revaluations"`); await q.query(`DROP TYPE "inventory_revaluation_status_enum"`); }
}
